# Generated by Django 5.2 on 2025-04-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurant_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
