# Generated by Django 5.2 on 2025-04-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_restaurant_imageurl_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
